---
title: "ADO PEC1"
author: "Jesús Cea García"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(SummarizedExperiment)
library(tidyverse)
library(POMA)
library(EnhancedVolcano)
```

https://rdrr.io/cran/specmine.datasets/man/cachexia.html

# Cargamos el csv de Cachexia

```{r}
cachexia <- read.csv("human_cachexia.csv", check.names = FALSE) 

cachexia$Cancer_Type <- sub("_.*", "", cachexia$`Patient ID`) # Nueva columna con tipo de cáncer

cachexia <- cachexia %>% relocate(Cancer_Type, .after = 2) # La colocamos la tercera por comodidad

cachexia$`Patient ID`[cachexia$`Muscle loss` == "cachexic"] <- paste0("CA-", 1:sum(cachexia$`Muscle loss` == "cachexic")) #Los renombramos de una manera más visible
cachexia$`Patient ID`[cachexia$`Muscle loss` == "control"] <- paste0("CT-", 1:sum(cachexia$`Muscle loss` == "control"))

```


# Preparamos el SummarizedExperiment

```{r}
# Obtenemos los metadatos de las muestras
sample_metadata <- cachexia[, 1:3]

rownames(sample_metadata) <- cachexia$`Patient ID`
```

```{r}
# Preparamos la matriz de expresión de los metabolitos
expr_matrix <- as.matrix(cachexia[, -(1:3)])
rownames(expr_matrix) <- sample_metadata$`Patient ID` # Mismo orden

expr_matrix <- t(expr_matrix)
```

```{r}
# Crear SummarizedExperiment
se <- SummarizedExperiment(
  assays = list(counts = expr_matrix),
  colData = sample_metadata
)
se
```

```{r}
colData(se)
```



```{r}
table(cachexia$`Muscle loss`)
```


```{r}
# Acceder a la matriz de expresión
expr_unn <- assay(se)  # si solo tienes una matriz en assays(se)

# Asegúrate de que el orden de colores coincida con las columnas de expr
grupos <- colData(se)$`Muscle loss`  # por ejemplo
colores <- ifelse(grupos == "cachexic", "red", "blue")

# Crear boxplot
boxplot(expr_unn,
        las = 2,
        col = colores,
        cex.axis = 0.8,
        main = "Distribución de los valores de expresión")
```

```{r}
#Normalización
expr_norm <- log2(assay(se))
# Crear boxplot
boxplot(expr_norm,
        las = 2,
        col = colores,
        cex.axis = 0.8,
        main = "Distribución de los valores de expresión")
```


```{r}
# Obtener expresión y grupos
grupo <- colData(se)$`Muscle loss`
# Calcular medianas por muestra
medianas <- apply(expr_norm, 2, median)

# Crear boxplot por grupo
boxplot(medianas ~ grupo,
        col = c("red", "blue"),
        main = "Mediana de concentración por grupo",
        ylab = "Mediana de concentración")

```

# PCA

```{r}
pc <-prcomp(t(expr_norm), scale=FALSE)
loads <- round(pc$sdev^2 / sum(pc$sdev^2) * 100, 1)
```



```{r}
pacientes_ID <- cachexia[ ,1]

xlab<-c(paste("PC1",loads[1],"%"))
ylab<-c(paste("PC2",loads[2],"%"))

plot(pc$x[,1:2],xlab=xlab,ylab=ylab, col=colores, 
     main ="Principal components (PCA)")

legend("topright", inset=c(-0.06,0),  # mueve la leyenda fuera
       legend=c("cachexia", "control"), 
       col=c("red", "blue"), 
       pch=19, xpd=TRUE)

text(pc$x[,1],pc$x[,2],pacientes_ID, pos=3, cex=.6)
```
# Batch Effect

```{r}
grupo_batch <- colData(se)$Cancer_Type
colores_batch <- ifelse(grupo_batch == "PIF", "red",
                  ifelse(grupo_batch == "NETCR", "blue",
                         "green"))

plot(pc$x[,1:2],xlab=xlab,ylab=ylab, col=colores_batch, 
     main ="Principal components (PCA)")

legend("topright", inset=c(-0.05,0),  # mueve la leyenda fuera
       legend=c("PIF", "NETCR", "NETCL"), 
       col=c("red", "blue", "green"), 
       pch=19, xpd=TRUE)

text(pc$x[,1],pc$x[,2],pacientes_ID, pos=3, cex=.6)
```


# Dendograma

```{r}
# Distancia y clustering jerárquico
d <- dist(t(expr_norm))  # si estás usando un SummarizedExperiment
hc <- hclust(d, method = "average")

# Dibujar dendrograma
hc$labels <- gsub("_.*", "", hc$labels)  
plot(hc, main = "Dendrograma por tipo de muestra", cex = 0.7)
rect.hclust(hc, k = 2, border = c("red", "blue"))

```

# DEG
```{r}
ttest <- function(x) {
  tt = t.test(x[1:47], x[48:77])
  return(c(
    t = tt$statistic,
    p.value = tt$p.value,
    log2FC = log2(mean(x[1:47]) / mean(x[48:77]))
  ))
}

ans <- apply(expr_norm, 1, ttest)
```



```{r}
# Convertimos la matriz a data.frame
ttest_df <- as.data.frame(t(ans))

# Añadir nombres de los metabolitos (features)
ttest_df$feature <- rownames(ttest_df)
```


```{r}
EnhancedVolcano(ttest_df,
                lab = ttest_df$feature,
                x = 'log2FC',
                y = 'p.value',
                pCutoff = 0.05,
                FCcutoff = 0.5,  # más sensible
                pointSize = 2,
                labSize = 3,
                title = 'Volcano Plot - Metabolitos')

```






